name:                iruka
version:             0.1.0.0
github:              "evuez/iruka"
license:             BSD3
author:              "evuez"
maintainer:          "helloevuez@gmail.com"
copyright:           "2020 evuez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/evuez/iruka#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- aeson

library:
  source-dirs: src

executables:
  iruka:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iruka

tests:
  iruka-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iruka
    - hspec
    - hspec-megaparsec
